version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: verum
      POSTGRES_PASSWORD: verum
      POSTGRES_DB: verumoverview
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
