version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-verum}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-verum}
      POSTGRES_DB: ${POSTGRES_DB:-verumoverview}
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - verum-net

  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-verum}:${POSTGRES_PASSWORD:-verum}@db:5432/${POSTGRES_DB:-verumoverview}
    networks:
      - verum-net

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000
    networks:
      - verum-net

networks:
  verum-net:
    driver: bridge
volumes:
  db-data:
